cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allowed_headers:
    - "*"
  allow_credentials: true

cookie:
  domain: "localhost"
  http_only: true
  secure: true
  same_site: "lax"
  partitioned: true

